nome = str(input('digite seu nome completo: ')).strip()
print('analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {}'.format(nome.find(' ')))
separa = nome.split()
print (separa)
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))
